name: Vite React App CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Preview
        run: npm run preview

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Hosting Platform
        # Add your deployment step here, for example:
        # run: npm run deploy
